apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  #namespace: todo
  labels:
    type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app 
  template:
    metadata:
      labels:
        app: todo 
        type: app
    spec:

      containers:
      - name: todo-app
        image: {{ .Values.Appimage }} #note that it may not be good latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi" 
            cpu: "250m" 
          limits:
            memory: "128Mi"
            cpu: "500m" 
