{{- if eq .Values.service.type "ClusterIP" }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  #namespace: todo
spec:
  selector:
    app: todo
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
#  externalIPs:
#    - 198.51.100.32
{{- end }}
